//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLTestApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XMLTestApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Configuration&gt;
        ///	&lt;ProductType1&gt;
        ///    &lt;Name&gt;Product1&lt;/Name&gt;
        ///    &lt;Id&gt;100&lt;/Id&gt;
        ///    &lt;checksum&gt;1a&lt;/checksum&gt;
        ///    &lt;Var1&gt;0&lt;/Var1&gt;
        ///    &lt;Var2&gt;3&lt;/Var2&gt;
        ///    &lt;Var3&gt;Family1&lt;/Var3&gt;
        ///    &lt;Subproduct&gt;
        ///      &lt;Lenght&gt;8&lt;/Lenght&gt;
        ///      &lt;Area&gt;7&lt;/Area&gt;
        ///      &lt;NearPoint&gt;0;-8&lt;/NearPoint&gt;
        ///    &lt;/Subproduct&gt;
        ///    &lt;Subproduct&gt;
        ///      &lt;Lenght&gt;9&lt;/Lenght&gt;
        ///      &lt;Area&gt;5&lt;/Area&gt;
        ///      &lt;NearPoint&gt;2;-8&lt;/NearPoint&gt;
        ///    &lt;/Subproduct&gt;
        ///	&lt;/ProductType1&gt;
        ///	&lt;ProductType1&gt;
        ///    &lt;Name&gt;Product2&lt;/Nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLTest {
            get {
                return ResourceManager.GetString("XMLTest", resourceCulture);
            }
        }
    }
}
